# Build strings and fingerprints. Android version, security patch and chipset props always stay real.
FILE_ENABLED

ENABLED,ro.build.fingerprint,google/cheetah/cheetah:16/CP1A.260405.005/15001963:user/release-keys

ENABLED,ro.build.id,CP1A.260405.005
ENABLED,ro.build.display.id,CP1A.260405.005

ENABLED,ro.build.version.incremental,15001963
ENABLED,ro.build.type,user
ENABLED,ro.build.tags,release-keys
ENABLED,ro.build.description,cheetah-user 16 CP1A.260405.005 15001963 release-keys

# Product build props
ENABLED,ro.product.build.fingerprint,google/cheetah/cheetah:16/CP1A.260405.005/15001963:user/release-keys
ENABLED,ro.product.build.id,CP1A.260405.005
ENABLED,ro.product.build.tags,release-keys
ENABLED,ro.product.build.type,user
ENABLED,ro.product.build.version.incremental,15001963

# Partition fingerprints
ENABLED,ro.system.build.fingerprint,google/cheetah/cheetah:16/CP1A.260405.005/15001963:user/release-keys
ENABLED,ro.system_ext.build.fingerprint,google/cheetah/cheetah:16/CP1A.260405.005/15001963:user/release-keys
ENABLED,ro.vendor.build.fingerprint,google/cheetah/cheetah:16/CP1A.260405.005/15001963:user/release-keys
ENABLED,ro.vendor.build.id,CP1A.260405.005
ENABLED,ro.vendor.build.version.incremental,15001963
ENABLED,ro.vendor.build.tags,release-keys
ENABLED,ro.vendor.build.type,user
ENABLED,ro.odm.build.fingerprint,google/cheetah/cheetah:16/CP1A.260405.005/15001963:user/release-keys
ENABLED,ro.odm.build.version.incremental,15001963

ENABLED,ro.build.flavor,cheetah-user
