# Device identity. Format: ENABLED|DISABLED,prop.name,value
FILE_ENABLED

ENABLED,ro.product.brand,google
ENABLED,ro.product.manufacturer,Google
ENABLED,ro.product.model,Pixel 7 Pro

# Product partition
ENABLED,ro.product.product.brand,google
ENABLED,ro.product.product.manufacturer,Google
ENABLED,ro.product.product.model,Pixel 7 Pro

# System partition
ENABLED,ro.product.system.brand,google
ENABLED,ro.product.system.manufacturer,Google
ENABLED,ro.product.system.model,Pixel 7 Pro

# System_ext partition
ENABLED,ro.product.system_ext.brand,google
ENABLED,ro.product.system_ext.manufacturer,Google
ENABLED,ro.product.system_ext.model,Pixel 7 Pro
