# Device identity. Format: ENABLED|DISABLED,prop.name,value
FILE_ENABLED

ENABLED,ro.product.brand,google
ENABLED,ro.product.manufacturer,Google
ENABLED,ro.product.model,Pixel 7 Pro
ENABLED,ro.product.name,cheetah
ENABLED,ro.product.device,cheetah
ENABLED,ro.product.board,cheetah

# Product partition
ENABLED,ro.product.product.brand,google
ENABLED,ro.product.product.manufacturer,Google
ENABLED,ro.product.product.model,Pixel 7 Pro
ENABLED,ro.product.product.name,cheetah
ENABLED,ro.product.product.device,cheetah

# System partition
ENABLED,ro.product.system.brand,google
ENABLED,ro.product.system.manufacturer,Google
ENABLED,ro.product.system.model,Pixel 7 Pro
ENABLED,ro.product.system.name,cheetah
ENABLED,ro.product.system.device,cheetah

# System_ext partition
ENABLED,ro.product.system_ext.brand,google
ENABLED,ro.product.system_ext.manufacturer,Google
ENABLED,ro.product.system_ext.model,Pixel 7 Pro
ENABLED,ro.product.system_ext.name,cheetah
ENABLED,ro.product.system_ext.device,cheetah

# Vendor partition
ENABLED,ro.product.vendor.brand,google
ENABLED,ro.product.vendor.manufacturer,Google
ENABLED,ro.product.vendor.model,Pixel 7 Pro
ENABLED,ro.product.vendor.name,cheetah
ENABLED,ro.product.vendor.device,cheetah

# ODM partition
ENABLED,ro.product.odm.brand,google
ENABLED,ro.product.odm.manufacturer,Google
ENABLED,ro.product.odm.model,Pixel 7 Pro
ENABLED,ro.product.odm.name,cheetah
ENABLED,ro.product.odm.device,cheetah
